<a href="https://colab.research.google.com/github/NILEG/TensorFlow/blob/main/NLP_000.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [6]:
sentences=["I love bananas",
           "We will work together",
           "We will visit tomorrow"]

#initializing Tokenizer
tokenizer=tf.keras.preprocessing.text.Tokenizer(num_words=100)
#Fitting tokenizer on text
tokenizer.fit_on_texts(sentences)
word_index=tokenizer.word_index
#Replacing words in sentences with generated tokens
sequences=tokenizer.texts_to_sequences(sentences)
print(word_index)
print(sequences)

{'we': 1, 'will': 2, 'i': 3, 'love': 4, 'bananas': 5, 'work': 6, 'together': 7, 'visit': 8, 'tomorrow': 9}
[[3, 4, 5], [1, 2, 6, 7], [1, 2, 8, 9]]


####Out of vocabulary words

In [8]:
sequences_normal=tokenizer.texts_to_sequences(["I love blue sky"])
print(sequences_normal)
#Only I(3) and love(4) exsists in the vocabulary thats why got got only them

[[3, 4]]


In [15]:
#Solution
new_tokenizer=tf.keras.preprocessing.text.Tokenizer(num_words=100, oov_token="<OOV>")
new_tokenizer.fit_on_texts(sentences)
print(new_tokenizer.word_index)
sequences=new_tokenizer.texts_to_sequences(["I love blue sky"])
print(sequences)

{'<OOV>': 1, 'we': 2, 'will': 3, 'i': 4, 'love': 5, 'bananas': 6, 'work': 7, 'together': 8, 'visit': 9, 'tomorrow': 10}
[[4, 5, 1, 1]]


####Padding

In [18]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

sentences=["I love bananas",
           "We will work together",
           "We will visit tomorrow",
           "This is a very big and long sentence"]

tokenizer2=tf.keras.preprocessing.text.Tokenizer(num_words=100, oov_token="<OOV>")
new_tokenizer.fit_on_texts(sentences)
sequences=new_tokenizer.texts_to_sequences(sentences)

pad_seq=pad_sequences(sequences, padding="post")

#post: 0 will be added after sentence. Default to pre
#maxlen: max length of the sentences. Longer sentences will be truncated
#truncating="post": longer sentences will be truncated from the end; not from the start
print(pad_seq)

[[ 4  5  6  0  0  0  0  0]
 [ 2  3  7  8  0  0  0  0]
 [ 2  3  9 10  0  0  0  0]
 [11 12 13 14 15 16 17 18]]
